# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Finder' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Finder

  pod ‘Firebase/Database’
  pod ‘Firebase/Core’
  pod ‘Firebase/Auth’
  pod ‘Firebase/Messaging’
  pod 'Cloudinary'
  pod 'MBProgressHUD', '~> 1.0.0'
end
